-- LexiTube schema v4 for Postgres (Netlify Database).
-- Same model as db/schema.sql (SQLite, local). Timestamps are ISO-8601 text
-- (UTC, "...Z") in both, so the application code is identical on either side.

CREATE TABLE IF NOT EXISTS users (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT    NOT NULL DEFAULT 'Learner',
  daily_goal    INTEGER NOT NULL DEFAULT 10,
  speak_arabic  INTEGER NOT NULL DEFAULT 0,
  speech_rate   DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  username      TEXT,
  password_hash TEXT,
  created_at    TEXT    NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE TABLE IF NOT EXISTS sources (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind               TEXT    NOT NULL CHECK (kind IN ('youtube','text')),
  youtube_id         TEXT UNIQUE,
  url                TEXT,
  title              TEXT    NOT NULL,
  channel            TEXT,
  duration_seconds   INTEGER,
  thumbnail_url      TEXT,
  transcript_source  TEXT,
  extractor          TEXT,
  word_count         INTEGER,
  is_demo            INTEGER NOT NULL DEFAULT 0,
  translation_status TEXT    NOT NULL DEFAULT 'none',
  ai_cursor          INTEGER NOT NULL DEFAULT 0,
  created_at         TEXT    NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
  analyzed_at        TEXT    NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE TABLE IF NOT EXISTS transcript_lines (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id     INTEGER NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
  idx           INTEGER NOT NULL,
  start_seconds DOUBLE PRECISION,
  duration      DOUBLE PRECISION,
  text          TEXT    NOT NULL,
  text_ar       TEXT,
  UNIQUE (source_id, idx)
);

CREATE TABLE IF NOT EXISTS vocabulary (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  term            TEXT    NOT NULL,
  match_key       TEXT    NOT NULL UNIQUE,
  item_type       TEXT    NOT NULL DEFAULT 'word',
  part_of_speech  TEXT,
  level           TEXT CHECK (level IS NULL OR level IN ('A1','A2','B1','B2','C1','C2')),
  band            TEXT,
  usefulness      INTEGER,
  pronunciation   TEXT,
  arabic          TEXT,
  simple_english  TEXT,
  similar_json    TEXT    NOT NULL DEFAULT '[]',
  topic           TEXT,
  origin          TEXT,
  created_at      TEXT    NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE TABLE IF NOT EXISTS examples (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vocabulary_id INTEGER NOT NULL REFERENCES vocabulary(id) ON DELETE CASCADE,
  kind          TEXT    NOT NULL DEFAULT 'example',
  sentence      TEXT    NOT NULL,
  sentence_key  TEXT    NOT NULL,
  arabic        TEXT,
  UNIQUE (vocabulary_id, sentence_key)
);

CREATE TABLE IF NOT EXISTS occurrences (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vocabulary_id      INTEGER NOT NULL REFERENCES vocabulary(id) ON DELETE CASCADE,
  source_id          INTEGER NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
  line_id            INTEGER REFERENCES transcript_lines(id) ON DELETE CASCADE,
  char_start         INTEGER,
  char_end           INTEGER,
  sentence           TEXT    NOT NULL,
  sentence_ar        TEXT,
  contextual_meaning TEXT,
  context_note       TEXT,
  timestamp_seconds  INTEGER,
  suggested          INTEGER NOT NULL DEFAULT 0,
  rank               INTEGER NOT NULL DEFAULT 0,
  UNIQUE (source_id, vocabulary_id, line_id)
);

CREATE TABLE IF NOT EXISTS user_vocabulary (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id           INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  vocabulary_id     INTEGER NOT NULL REFERENCES vocabulary(id) ON DELETE CASCADE,
  occurrence_id     INTEGER REFERENCES occurrences(id) ON DELETE SET NULL,
  source_id         INTEGER REFERENCES sources(id) ON DELETE SET NULL,
  state             TEXT    NOT NULL DEFAULT 'saved' CHECK (state IN ('saved','dismissed')),
  user_arabic       TEXT,
  saved_at          TEXT    NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
  review_count      INTEGER NOT NULL DEFAULT 0,
  correct_count     INTEGER NOT NULL DEFAULT 0,
  wrong_count       INTEGER NOT NULL DEFAULT 0,
  streak_correct    INTEGER NOT NULL DEFAULT 0,
  lapses            INTEGER NOT NULL DEFAULT 0,
  ease              DOUBLE PRECISION NOT NULL DEFAULT 2.5,
  interval_days     DOUBLE PRECISION NOT NULL DEFAULT 0,
  mastery           INTEGER NOT NULL DEFAULT 0,
  difficulty        DOUBLE PRECISION NOT NULL DEFAULT 0,
  recent            TEXT    NOT NULL DEFAULT '',
  last_wrong_at     TEXT,
  last_reviewed_at  TEXT,
  next_review_at    TEXT,
  UNIQUE (user_id, vocabulary_id)
);

CREATE TABLE IF NOT EXISTS review_logs (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id            INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  user_vocabulary_id INTEGER NOT NULL REFERENCES user_vocabulary(id) ON DELETE CASCADE,
  source             TEXT    NOT NULL,
  grade              TEXT    NOT NULL,
  correct            INTEGER NOT NULL,
  interval_after     DOUBLE PRECISION,
  created_at         TEXT    NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE TABLE IF NOT EXISTS daily_plans (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  plan_date  TEXT    NOT NULL,
  created_at TEXT    NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
  UNIQUE (user_id, plan_date)
);

CREATE TABLE IF NOT EXISTS daily_plan_items (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id            INTEGER NOT NULL REFERENCES daily_plans(id) ON DELETE CASCADE,
  user_vocabulary_id INTEGER NOT NULL REFERENCES user_vocabulary(id) ON DELETE CASCADE,
  bucket             TEXT    NOT NULL,
  position           INTEGER NOT NULL,
  completed_at       TEXT,
  UNIQUE (plan_id, user_vocabulary_id)
);

CREATE TABLE IF NOT EXISTS word_groups (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name       TEXT    NOT NULL,
  color      TEXT,
  created_at TEXT    NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_word_groups_name ON word_groups (user_id, lower(name));

CREATE TABLE IF NOT EXISTS word_group_items (
  group_id           INTEGER NOT NULL REFERENCES word_groups(id) ON DELETE CASCADE,
  user_vocabulary_id INTEGER NOT NULL REFERENCES user_vocabulary(id) ON DELETE CASCADE,
  added_at           TEXT    NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
  PRIMARY KEY (group_id, user_vocabulary_id)
);

CREATE TABLE IF NOT EXISTS ai_cache (
  key        TEXT PRIMARY KEY,
  task       TEXT NOT NULL,
  model      TEXT,
  response   TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

-- Server-side backups taken before every data import (JSON snapshot).
CREATE TABLE IF NOT EXISTS backups (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reason     TEXT NOT NULL,
  payload    TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE INDEX IF NOT EXISTS idx_lines_source      ON transcript_lines(source_id, idx);
CREATE INDEX IF NOT EXISTS idx_occ_source        ON occurrences(source_id, line_id);
CREATE INDEX IF NOT EXISTS idx_occ_vocab         ON occurrences(vocabulary_id);
CREATE INDEX IF NOT EXISTS idx_examples_vocab    ON examples(vocabulary_id);
CREATE INDEX IF NOT EXISTS idx_uv_user_next      ON user_vocabulary(user_id, next_review_at);
CREATE INDEX IF NOT EXISTS idx_uv_user_saved     ON user_vocabulary(user_id, saved_at);
CREATE INDEX IF NOT EXISTS idx_uv_user_difficult ON user_vocabulary(user_id, difficulty);
CREATE INDEX IF NOT EXISTS idx_uv_source         ON user_vocabulary(source_id);
CREATE INDEX IF NOT EXISTS idx_logs_user_time    ON review_logs(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_logs_uv           ON review_logs(user_vocabulary_id, id);
CREATE INDEX IF NOT EXISTS idx_group_items_uv    ON word_group_items(user_vocabulary_id);
