-- LexiTube schema for PostgreSQL / Supabase.
-- Same tables and columns as db/schema.sql (the SQLite schema the server runs
-- today), so the data layer in server/repo.js maps 1:1 when moving to Postgres.
-- In Supabase, `users.id` can reference auth.users and RLS can scope every
-- table to auth.uid() (example policies at the bottom).

create table if not exists users (
  id            bigint generated by default as identity primary key,
  auth_user_id  uuid unique,            -- optional link to auth.users(id)
  name          text    not null default 'Learner',
  daily_goal    integer not null default 10,
  speak_arabic  boolean not null default false,
  speech_rate   real    not null default 1.0,
  created_at    timestamptz not null default now()
);

create table if not exists videos (
  id                bigint generated by default as identity primary key,
  youtube_id        text not null unique,
  url               text not null,
  title             text not null,
  channel           text,
  duration_seconds  integer,
  thumbnail_url     text,
  transcript_source text,
  extractor         text,
  word_count        integer,
  is_demo           boolean not null default false,
  analyzed_at       timestamptz not null default now()
);

create table if not exists vocabulary (
  id             bigint generated by default as identity primary key,
  term           text not null,
  term_key       text not null,
  item_type      text not null default 'word',
  part_of_speech text,
  level          text not null check (level in ('B1','B2','C1')),
  usefulness     integer not null default 70,
  pronunciation  text,
  arabic         text not null,
  simple_english text not null,
  similar_json   jsonb not null default '[]',
  topic          text,
  created_at     timestamptz not null default now(),
  unique nulls not distinct (term_key, part_of_speech)
);

create table if not exists examples (
  id            bigint generated by default as identity primary key,
  vocabulary_id bigint not null references vocabulary(id) on delete cascade,
  kind          text not null default 'example',
  sentence      text not null,
  arabic        text
);

create table if not exists video_vocabulary (
  id                 bigint generated by default as identity primary key,
  video_id           bigint not null references videos(id) on delete cascade,
  vocabulary_id      bigint not null references vocabulary(id) on delete cascade,
  context_sentence   text not null,
  context_arabic     text,
  contextual_meaning text,
  timestamp_seconds  integer,
  rank               integer not null default 0,
  unique (video_id, vocabulary_id)
);

create table if not exists user_vocabulary (
  id                  bigint generated by default as identity primary key,
  user_id             bigint not null references users(id) on delete cascade,
  vocabulary_id       bigint not null references vocabulary(id) on delete cascade,
  video_vocabulary_id bigint references video_vocabulary(id) on delete set null,
  source_video_id     bigint references videos(id) on delete set null,
  state               text not null default 'saved' check (state in ('saved','dismissed')),
  saved_at            timestamptz not null default now(),
  review_count        integer not null default 0,
  correct_count       integer not null default 0,
  wrong_count         integer not null default 0,
  streak_correct      integer not null default 0,
  lapses              integer not null default 0,
  ease                real not null default 2.5,
  interval_days       real not null default 0,
  mastery             integer not null default 0,
  last_reviewed_at    timestamptz,
  next_review_at      timestamptz,
  unique (user_id, vocabulary_id)
);

create table if not exists review_logs (
  id                 bigint generated by default as identity primary key,
  user_id            bigint not null references users(id) on delete cascade,
  user_vocabulary_id bigint not null references user_vocabulary(id) on delete cascade,
  source             text not null,
  grade              text not null,
  correct            boolean not null,
  interval_after     real,
  created_at         timestamptz not null default now()
);

create table if not exists daily_plans (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references users(id) on delete cascade,
  plan_date  date not null,
  created_at timestamptz not null default now(),
  unique (user_id, plan_date)
);

create table if not exists daily_plan_items (
  id                 bigint generated by default as identity primary key,
  plan_id            bigint not null references daily_plans(id) on delete cascade,
  user_vocabulary_id bigint not null references user_vocabulary(id) on delete cascade,
  bucket             text not null,
  position           integer not null,
  completed_at       timestamptz,
  unique (plan_id, user_vocabulary_id)
);

create table if not exists campaigns (
  id          bigint generated by default as identity primary key,
  user_id     bigint not null references users(id) on delete cascade,
  name        text not null,
  description text,
  source_type text not null,
  source_ref  text,
  color       text,
  created_at  timestamptz not null default now()
);

create table if not exists campaign_items (
  campaign_id        bigint not null references campaigns(id) on delete cascade,
  user_vocabulary_id bigint not null references user_vocabulary(id) on delete cascade,
  primary key (campaign_id, user_vocabulary_id)
);

create index if not exists idx_uv_user_next   on user_vocabulary(user_id, next_review_at);
create index if not exists idx_uv_user_saved  on user_vocabulary(user_id, saved_at);
create index if not exists idx_logs_user_time on review_logs(user_id, created_at);
create index if not exists idx_vv_video       on video_vocabulary(video_id);
create index if not exists idx_examples_vocab on examples(vocabulary_id);

-- Example Supabase row-level security for per-learner tables:
-- alter table user_vocabulary enable row level security;
-- create policy "own rows" on user_vocabulary
--   using (user_id = (select id from users where auth_user_id = auth.uid()));
-- (repeat for review_logs, daily_plans, campaigns; daily_plan_items and
--  campaign_items via their parent row.)
