-- LexiTube schema v2 for PostgreSQL / Supabase.
-- Same tables, columns and constraints as db/schema.sql (SQLite, used by the
-- server today). The app currently runs on SQLite; moving to Postgres means
-- porting server/db.js + repo.js queries, not changing the data model.
--
-- Layers: global knowledge (vocabulary, examples) · sources (sources,
-- transcript_lines) · context (occurrences) · user knowledge (user_vocabulary,
-- review_logs, daily_plans) · organisation (word_groups, word_group_items).

create table if not exists users (
  id            bigint generated by default as identity primary key,
  auth_user_id  uuid unique,                      -- optional link to auth.users(id)
  name          text    not null default 'Learner',
  daily_goal    integer not null default 10,
  speak_arabic  boolean not null default false,
  speech_rate   real    not null default 1.0,
  created_at    timestamptz not null default now()
);

create table if not exists sources (
  id                 bigint generated by default as identity primary key,
  kind               text not null check (kind in ('youtube','text')),
  youtube_id         text unique,
  url                text,
  title              text not null,
  channel            text,
  duration_seconds   integer,
  thumbnail_url      text,
  transcript_source  text,
  extractor          text,
  word_count         integer,
  is_demo            boolean not null default false,
  translation_status text not null default 'none',
  created_at         timestamptz not null default now(),
  analyzed_at        timestamptz not null default now()
);

create table if not exists transcript_lines (
  id            bigint generated by default as identity primary key,
  source_id     bigint not null references sources(id) on delete cascade,
  idx           integer not null,
  start_seconds real,
  duration      real,
  text          text not null,
  text_ar       text,
  unique (source_id, idx)
);

create table if not exists vocabulary (
  id              bigint generated by default as identity primary key,
  term            text not null,
  match_key       text not null unique,
  item_type       text not null default 'word',
  part_of_speech  text,
  level           text check (level is null or level in ('A1','A2','B1','B2','C1','C2')),
  band            text,
  usefulness      integer,
  pronunciation   text,
  arabic          text,
  simple_english  text,
  similar_json    jsonb not null default '[]',
  topic           text,
  origin          text,
  created_at      timestamptz not null default now()
);

create table if not exists examples (
  id            bigint generated by default as identity primary key,
  vocabulary_id bigint not null references vocabulary(id) on delete cascade,
  kind          text not null default 'example',
  sentence      text not null,
  sentence_key  text not null,
  arabic        text,
  unique (vocabulary_id, sentence_key)
);

create table if not exists occurrences (
  id                 bigint generated by default as identity primary key,
  vocabulary_id      bigint not null references vocabulary(id) on delete cascade,
  source_id          bigint not null references sources(id) on delete cascade,
  line_id            bigint references transcript_lines(id) on delete cascade,
  char_start         integer,
  char_end           integer,
  sentence           text not null,
  sentence_ar        text,
  contextual_meaning text,
  timestamp_seconds  integer,
  suggested          boolean not null default false,
  rank               integer not null default 0,
  unique nulls not distinct (source_id, vocabulary_id, line_id)
);

create table if not exists user_vocabulary (
  id                bigint generated by default as identity primary key,
  user_id           bigint not null references users(id) on delete cascade,
  vocabulary_id     bigint not null references vocabulary(id) on delete cascade,
  occurrence_id     bigint references occurrences(id) on delete set null,
  source_id         bigint references sources(id) on delete set null,
  state             text not null default 'saved' check (state in ('saved','dismissed')),
  user_arabic       text,
  saved_at          timestamptz not null default now(),
  review_count      integer not null default 0,
  correct_count     integer not null default 0,
  wrong_count       integer not null default 0,
  streak_correct    integer not null default 0,
  lapses            integer not null default 0,
  ease              real not null default 2.5,
  interval_days     real not null default 0,
  mastery           integer not null default 0,
  difficulty        real not null default 0,
  recent            text not null default '',
  last_wrong_at     timestamptz,
  last_reviewed_at  timestamptz,
  next_review_at    timestamptz,
  unique (user_id, vocabulary_id)
);

create table if not exists review_logs (
  id                 bigint generated by default as identity primary key,
  user_id            bigint not null references users(id) on delete cascade,
  user_vocabulary_id bigint not null references user_vocabulary(id) on delete cascade,
  source             text not null,
  grade              text not null,
  correct            boolean not null,
  interval_after     real,
  created_at         timestamptz not null default now()
);

create table if not exists daily_plans (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references users(id) on delete cascade,
  plan_date  date not null,
  created_at timestamptz not null default now(),
  unique (user_id, plan_date)
);

create table if not exists daily_plan_items (
  id                 bigint generated by default as identity primary key,
  plan_id            bigint not null references daily_plans(id) on delete cascade,
  user_vocabulary_id bigint not null references user_vocabulary(id) on delete cascade,
  bucket             text not null,
  position           integer not null,
  completed_at       timestamptz,
  unique (plan_id, user_vocabulary_id)
);

create table if not exists word_groups (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references users(id) on delete cascade,
  name       text not null,
  color      text,
  created_at timestamptz not null default now()
);
create unique index if not exists word_groups_user_name on word_groups (user_id, lower(name));

create table if not exists word_group_items (
  group_id           bigint not null references word_groups(id) on delete cascade,
  user_vocabulary_id bigint not null references user_vocabulary(id) on delete cascade,
  added_at           timestamptz not null default now(),
  primary key (group_id, user_vocabulary_id)
);

create index if not exists idx_lines_source      on transcript_lines(source_id, idx);
create index if not exists idx_occ_source        on occurrences(source_id, line_id);
create index if not exists idx_occ_vocab         on occurrences(vocabulary_id);
create index if not exists idx_examples_vocab    on examples(vocabulary_id);
create index if not exists idx_uv_user_next      on user_vocabulary(user_id, next_review_at);
create index if not exists idx_uv_user_saved     on user_vocabulary(user_id, saved_at);
create index if not exists idx_uv_user_difficult on user_vocabulary(user_id, difficulty);
create index if not exists idx_logs_user_time    on review_logs(user_id, created_at);
create index if not exists idx_logs_uv           on review_logs(user_vocabulary_id, id);
create index if not exists idx_group_items_uv    on word_group_items(user_vocabulary_id);

-- Example Supabase row-level security for per-learner tables:
-- alter table user_vocabulary enable row level security;
-- create policy "own rows" on user_vocabulary
--   using (user_id = (select id from users where auth_user_id = auth.uid()));
-- (repeat for review_logs, daily_plans, word_groups; daily_plan_items and
--  word_group_items via their parent row.)
