// Compact B1–C1 dictionary used by the offline extractor (no AI key configured).
// [term, level, part of speech, item type, Arabic, simple English, topic, usefulness]
// Multi-word entries may contain "something"/"someone" slots, matched flexibly.

export const COMPACT = [
  ['accomplish', 'B2', 'verb', 'word', 'يُنجز / يحقّق', 'To succeed in doing something.', 'work', 80],
  ['accurate', 'B2', 'adjective', 'word', 'دقيق', 'Correct and exact.', 'academic', 82],
  ['acknowledge', 'C1', 'verb', 'word', 'يعترف بـ / يُقرّ', 'To accept that something is true.', 'business', 76],
  ['adapt', 'B2', 'verb', 'word', 'يتكيّف', 'To change to suit a new situation.', 'daily', 84],
  ['adequate', 'C1', 'adjective', 'word', 'كافٍ / مناسب', 'Enough or good enough.', 'academic', 70],
  ['advocate', 'C1', 'verb', 'word', 'يدافع عن / يؤيّد', 'To publicly support an idea.', 'media', 70],
  ['affordable', 'B2', 'adjective', 'word', 'في متناول اليد (سعره مناسب)', 'Cheap enough for people to buy.', 'daily', 82],
  ['allocate', 'C1', 'verb', 'word', 'يخصّص / يوزّع', 'To give a part of something for a purpose.', 'business', 72],
  ['alternative', 'B2', 'noun', 'word', 'بديل', 'Another choice.', 'daily', 84],
  ['anticipate', 'C1', 'verb', 'word', 'يتوقّع (ويستعد)', 'To expect something and prepare for it.', 'business', 74],
  ['apparently', 'B2', 'adverb', 'word', 'على ما يبدو', 'According to what you have heard.', 'daily', 80],
  ['appreciate', 'B1', 'verb', 'word', 'يقدّر', 'To be grateful for something.', 'daily', 86],
  ['appropriate', 'B2', 'adjective', 'word', 'مناسب / ملائم', 'Suitable for a situation.', 'work', 84],
  ['aspect', 'B2', 'noun', 'word', 'جانب', 'One part or feature of something.', 'academic', 80],
  ['assess', 'C1', 'verb', 'word', 'يقيّم', 'To judge the quality or value of something.', 'work', 76],
  ['attitude', 'B1', 'noun', 'word', 'موقف / سلوك', 'The way you think and feel about something.', 'emotions', 84],
  ['awareness', 'B2', 'noun', 'word', 'وعي', 'Knowing about something.', 'media', 80],
  ['back up', 'B2', 'verb', 'phrasal verb', 'يدعم / يساند', 'To support or prove what someone says.', 'daily', 78],
  ['barrier', 'B2', 'noun', 'word', 'عائق / حاجز', 'Something that stops progress.', 'daily', 78],
  ['be up to something', 'B2', 'verb phrase', 'expression', 'يكون منشغلًا بـ / ينوي', 'To be doing or planning something.', 'daily', 72],
  ['beneficial', 'B2', 'adjective', 'word', 'مفيد', 'Having a good effect.', 'academic', 78],
  ['bias', 'C1', 'noun', 'word', 'تحيّز', 'An unfair preference for or against something.', 'media', 76],
  ['boost', 'B2', 'verb', 'word', 'يعزّز / يرفع', 'To increase or improve something.', 'business', 82],
  ['by and large', 'C1', 'adverb phrase', 'idiom', 'بشكل عام', 'In general; mostly.', 'daily', 68],
  ['call off', 'B1', 'verb', 'phrasal verb', 'يلغي', 'To cancel an event.', 'daily', 82],
  ['capable', 'B2', 'adjective', 'word', 'قادر / كفء', 'Having the ability to do something.', 'work', 80],
  ['carry out', 'B2', 'verb', 'phrasal verb', 'يُجري / ينفّذ', 'To do a task, test or plan.', 'academic', 84],
  ['catch up', 'B1', 'verb', 'phrasal verb', 'يلحق / يعوّض ما فاته', 'To reach the same level as others.', 'daily', 84],
  ['challenge', 'B1', 'noun', 'word', 'تحدٍّ', 'Something difficult that tests ability.', 'daily', 86],
  ['clarify', 'B2', 'verb', 'word', 'يوضّح', 'To make something clearer.', 'work', 82],
  ['collaborate', 'B2', 'verb', 'word', 'يتعاون', 'To work together with others.', 'work', 82],
  ['commitment', 'B2', 'noun', 'word', 'التزام', 'A promise or strong dedication.', 'work', 82],
  ['comprehensive', 'C1', 'adjective', 'word', 'شامل', 'Including everything needed.', 'academic', 74],
  ['concept', 'B2', 'noun', 'word', 'مفهوم', 'An idea.', 'academic', 82],
  ['concern', 'B2', 'noun', 'word', 'قلق / اهتمام', 'A worry.', 'emotions', 82],
  ['confident', 'B1', 'adjective', 'word', 'واثق', 'Sure about your abilities.', 'emotions', 86],
  ['consequence', 'B2', 'noun', 'word', 'عاقبة / نتيجة', 'A result, often a bad one.', 'daily', 82],
  ['considerable', 'C1', 'adjective', 'word', 'كبير / معتبر', 'Large in amount.', 'academic', 72],
  ['contribute', 'B2', 'verb', 'word', 'يساهم', 'To help cause or give something.', 'work', 82],
  ['convince', 'B2', 'verb', 'word', 'يُقنع', 'To make someone believe something.', 'daily', 84],
  ['curious', 'B1', 'adjective', 'word', 'فضولي / متشوّق للمعرفة', 'Wanting to know about something.', 'emotions', 82],
  ['cut back on', 'B2', 'verb', 'phrasal verb', 'يقلّل من', 'To reduce how much you use or do.', 'daily', 80],
  ['deal with', 'B1', 'verb', 'phrasal verb', 'يتعامل مع', 'To take action to solve a problem.', 'daily', 90],
  ['decline', 'C1', 'verb', 'word', 'ينخفض / يرفض بأدب', 'To go down; to politely refuse.', 'business', 72],
  ['dedicated', 'B2', 'adjective', 'word', 'مُخلص / متفانٍ', 'Working hard because you care.', 'work', 78],
  ['demanding', 'B2', 'adjective', 'word', 'مُرهِق / يتطلّب الكثير', 'Needing a lot of time or effort.', 'work', 80],
  ['determine', 'B2', 'verb', 'word', 'يحدّد', 'To decide or find out.', 'academic', 80],
  ['diverse', 'B2', 'adjective', 'word', 'متنوّع', 'Very different from each other.', 'media', 76],
  ['drawback', 'C1', 'noun', 'word', 'عيب / سلبية', 'A disadvantage.', 'business', 76],
  ['eager', 'B2', 'adjective', 'word', 'متحمّس / متلهّف', 'Wanting very much to do something.', 'emotions', 80],
  ['emphasize', 'B2', 'verb', 'word', 'يؤكّد على', 'To show something is important.', 'academic', 80],
  ['encounter', 'C1', 'verb', 'word', 'يواجه / يصادف', 'To meet or experience something.', 'daily', 72],
  ['end up', 'B1', 'verb', 'phrasal verb', 'ينتهي به الأمر', 'To finally be in a place or situation.', 'daily', 88],
  ['enhance', 'C1', 'verb', 'word', 'يحسّن / يعزّز', 'To improve the quality of something.', 'business', 76],
  ['ensure', 'B2', 'verb', 'word', 'يضمن / يتأكّد', 'To make certain that something happens.', 'work', 84],
  ['essential', 'B2', 'adjective', 'word', 'أساسي / ضروري', 'Completely necessary.', 'daily', 84],
  ['estimate', 'B2', 'verb', 'word', 'يقدّر (تقريبًا)', 'To guess a number or amount.', 'business', 78],
  ['eventually', 'B1', 'adverb', 'word', 'في النهاية', 'After a long time.', 'daily', 86],
  ['exaggerate', 'B2', 'verb', 'word', 'يبالغ', 'To make something seem bigger than it is.', 'daily', 78],
  ['expertise', 'C1', 'noun', 'word', 'خبرة متخصصة', 'Special skill or knowledge.', 'work', 74],
  ['flexible', 'B2', 'adjective', 'word', 'مرن', 'Able to change easily.', 'work', 82],
  ['frustrated', 'B2', 'adjective', 'word', 'محبَط', 'Annoyed because you can’t do something.', 'emotions', 84],
  ['fundamental', 'C1', 'adjective', 'word', 'جوهري / أساسي', 'Basic and very important.', 'academic', 76],
  ['get along with', 'B1', 'verb', 'phrasal verb', 'يتفاهم مع / ينسجم مع', 'To have a friendly relationship.', 'daily', 86],
  ['get rid of', 'B1', 'verb phrase', 'expression', 'يتخلّص من', 'To remove or throw away.', 'daily', 88],
  ['give up', 'B1', 'verb', 'phrasal verb', 'يستسلم / يتخلّى عن', 'To stop trying.', 'daily', 90],
  ['go through', 'B2', 'verb', 'phrasal verb', 'يمرّ بـ (تجربة صعبة)', 'To experience something difficult.', 'emotions', 84],
  ['gradually', 'B2', 'adverb', 'word', 'تدريجيًا', 'Slowly over time.', 'daily', 82],
  ['hands-on', 'B2', 'adjective', 'word', 'عملي / تطبيقي', 'Learning by doing.', 'work', 76],
  ['hesitate', 'B2', 'verb', 'word', 'يتردد', 'To pause before doing something.', 'emotions', 82],
  ['highlight', 'B2', 'verb', 'word', 'يسلّط الضوء على', 'To show something is important.', 'media', 80],
  ['impact', 'B2', 'noun', 'word', 'تأثير', 'A strong effect.', 'media', 86],
  ['implement', 'C1', 'verb', 'word', 'ينفّذ / يطبّق', 'To put a plan into action.', 'business', 76],
  ['imply', 'C1', 'verb', 'word', 'يُلمّح / يعني ضمنيًا', 'To suggest without saying directly.', 'academic', 72],
  ['in a nutshell', 'B2', 'adverb phrase', 'idiom', 'باختصار', 'In very few words.', 'daily', 78],
  ['in terms of', 'B2', 'preposition', 'expression', 'من حيث', 'When talking about.', 'academic', 84],
  ['incentive', 'C1', 'noun', 'word', 'حافز', 'Something that encourages you.', 'business', 74],
  ['inevitable', 'C1', 'adjective', 'word', 'حتمي / لا مفرّ منه', 'Certain to happen.', 'academic', 74],
  ['insight', 'C1', 'noun', 'word', 'فهم عميق / رؤية', 'A clear, deep understanding.', 'media', 76],
  ['interpret', 'B2', 'verb', 'word', 'يفسّر', 'To explain the meaning of something.', 'academic', 76],
  ['keep in mind', 'B1', 'verb phrase', 'expression', 'يضع في الاعتبار', 'To remember and consider.', 'daily', 88],
  ['lack', 'B2', 'noun', 'word', 'نقص / افتقار', 'Not having enough of something.', 'daily', 82],
  ['let down', 'B2', 'verb', 'phrasal verb', 'يخذل', 'To disappoint someone.', 'emotions', 80],
  ['look forward to', 'B1', 'verb', 'phrasal verb', 'يتطلّع إلى', 'To feel happy about a future event.', 'daily', 90],
  ['look into', 'B2', 'verb', 'phrasal verb', 'يبحث في / يتحقّق من', 'To investigate.', 'work', 82],
  ['maintain', 'B2', 'verb', 'word', 'يحافظ على', 'To keep something the same.', 'work', 82],
  ['make up your mind', 'B1', 'verb phrase', 'idiom', 'يحسم أمره / يقرّر', 'To decide.', 'daily', 84],
  ['meaningful', 'B2', 'adjective', 'word', 'ذو معنى / هادف', 'Important and valuable.', 'emotions', 78],
  ['mindset', 'B2', 'noun', 'word', 'عقلية / طريقة تفكير', 'A way of thinking.', 'emotions', 80],
  ['moreover', 'B2', 'adverb', 'word', 'علاوة على ذلك', 'Also; in addition.', 'academic', 76],
  ['motivated', 'B1', 'adjective', 'word', 'متحمّس / لديه دافع', 'Wanting to do something.', 'emotions', 86],
  ['nevertheless', 'B2', 'adverb', 'word', 'ومع ذلك', 'Despite what was just said.', 'academic', 76],
  ['obstacle', 'B2', 'noun', 'word', 'عقبة', 'Something that blocks your way.', 'daily', 80],
  ['obvious', 'B1', 'adjective', 'word', 'واضح / بديهي', 'Easy to see or understand.', 'daily', 84],
  ['opportunity', 'B1', 'noun', 'word', 'فرصة', 'A chance to do something.', 'work', 88],
  ['outstanding', 'B2', 'adjective', 'word', 'متميّز / ممتاز', 'Extremely good.', 'work', 78],
  ['overcome', 'B2', 'verb', 'word', 'يتغلّب على', 'To succeed in dealing with a problem.', 'emotions', 86],
  ['overlook', 'C1', 'verb', 'word', 'يغفل عن / يتجاهل', 'To fail to notice.', 'work', 74],
  ['particularly', 'B1', 'adverb', 'word', 'خاصةً / بشكل خاص', 'Especially.', 'daily', 84],
  ['perspective', 'B2', 'noun', 'word', 'وجهة نظر / منظور', 'A way of seeing something.', 'media', 84],
  ['potential', 'B2', 'noun', 'word', 'إمكانات / قدرة كامنة', 'Ability that may develop.', 'work', 84],
  ['precisely', 'B2', 'adverb', 'word', 'بالضبط', 'Exactly.', 'academic', 76],
  ['pursue', 'C1', 'verb', 'word', 'يسعى وراء', 'To try to achieve something.', 'work', 78],
  ['put off', 'B1', 'verb', 'phrasal verb', 'يؤجّل', 'To delay doing something.', 'daily', 86],
  ['put up with', 'B2', 'verb', 'phrasal verb', 'يتحمّل / يصبر على', 'To accept something unpleasant.', 'daily', 84],
  ['regardless', 'B2', 'adverb', 'word', 'بغض النظر', 'Without being affected by.', 'daily', 78],
  ['relevant', 'B2', 'adjective', 'word', 'ذو صلة', 'Connected to what is being discussed.', 'academic', 82],
  ['reliable', 'B2', 'adjective', 'word', 'موثوق', 'Can be trusted.', 'work', 84],
  ['resilient', 'C1', 'adjective', 'word', 'صامد / سريع التعافي', 'Able to recover quickly from problems.', 'emotions', 74],
  ['resource', 'B2', 'noun', 'word', 'مورد / مصدر', 'Something useful you can use.', 'work', 80],
  ['run out of', 'B1', 'verb', 'phrasal verb', 'ينفد منه', 'To have no more of something.', 'daily', 86],
  ['scenario', 'B2', 'noun', 'word', 'سيناريو / احتمال', 'A possible situation.', 'business', 76],
  ['set up', 'B1', 'verb', 'phrasal verb', 'يؤسّس / يجهّز', 'To start or prepare something.', 'business', 86],
  ['shift', 'B2', 'noun', 'word', 'تحوّل / تغيّر', 'A change.', 'media', 78],
  ['so far', 'B1', 'adverb phrase', 'expression', 'حتى الآن', 'Until now.', 'daily', 86],
  ['sort out', 'B2', 'verb', 'phrasal verb', 'يحلّ / يرتّب', 'To solve or organize.', 'daily', 82],
  ['spot', 'B2', 'verb', 'word', 'يلاحظ / يكتشف', 'To notice something.', 'daily', 80],
  ['strategy', 'B2', 'noun', 'word', 'استراتيجية / خطة', 'A plan to achieve a goal.', 'business', 82],
  ['substantial', 'C1', 'adjective', 'word', 'كبير / جوهري', 'Large in size or importance.', 'business', 72],
  ['sufficient', 'B2', 'adjective', 'word', 'كافٍ', 'Enough.', 'academic', 76],
  ['sustainable', 'B2', 'adjective', 'word', 'مستدام', 'Able to continue for a long time.', 'media', 78],
  ['take advantage of', 'B1', 'verb phrase', 'expression', 'يستغلّ / يستفيد من', 'To use an opportunity.', 'daily', 88],
  ['take over', 'B2', 'verb', 'phrasal verb', 'يتولّى / يستحوذ', 'To take control.', 'business', 80],
  ['tend to', 'B1', 'verb', 'expression', 'يميل إلى', 'To usually do something.', 'daily', 88],
  ['thorough', 'B2', 'adjective', 'word', 'دقيق / شامل', 'Careful and complete.', 'work', 78],
  ['tremendous', 'B2', 'adjective', 'word', 'هائل', 'Very great.', 'media', 76],
  ['ultimately', 'B2', 'adverb', 'word', 'في نهاية المطاف', 'Finally; in the end.', 'academic', 80],
  ['underestimate', 'C1', 'verb', 'word', 'يستهين بـ / يقلّل من شأن', 'To think something is smaller than it is.', 'daily', 78],
  ['undertake', 'C1', 'verb', 'word', 'يتولّى / يضطلع بـ', 'To start a task.', 'work', 70],
  ['unprecedented', 'C1', 'adjective', 'word', 'غير مسبوق', 'Never happened before.', 'media', 74],
  ['valuable', 'B1', 'adjective', 'word', 'قيّم', 'Very useful or important.', 'daily', 84],
  ['vulnerable', 'C1', 'adjective', 'word', 'ضعيف / معرّض للأذى', 'Easily hurt or harmed.', 'emotions', 76],
  ['whereas', 'B2', 'conjunction', 'word', 'بينما', 'Used to compare two different facts.', 'academic', 78],
  ['work out', 'B1', 'verb', 'phrasal verb', 'يحلّ / ينجح / يتمرّن', 'To solve; to succeed; to exercise.', 'daily', 86],
  ['worthwhile', 'B2', 'adjective', 'word', 'يستحق العناء', 'Worth the time or effort.', 'daily', 80],
];
