// Hand-written, fully-detailed B1–C1 entries. Used for demo data and as the
// highest-quality part of the offline dictionary extractor.
// similar: easier words with (roughly) the same meaning; `note` explains the difference.

export const RICH = [
  // ---------- Video 1: workplace / productivity ----------
  {
    term: 'reluctant', item_type: 'word', part_of_speech: 'adjective', level: 'B2', usefulness: 88, topic: 'emotions',
    pronunciation: '/rɪˈlʌktənt/', arabic: 'متردد / غير راغب', simple_english: 'Not wanting to do something.',
    similar: [
      { word: 'not willing', arabic: 'غير راغب' },
      { word: 'hesitant', arabic: 'متردد', note: 'hesitant = you pause before acting; reluctant = you don’t really want to.' },
      { word: 'unsure', arabic: 'غير متأكد', note: 'unsure is about doubt, not about wanting.' },
    ],
    example: 'Many employees are reluctant to share their ideas in big meetings.',
    example_arabic: 'كثير من الموظفين مترددون في مشاركة أفكارهم في الاجتماعات الكبيرة.',
    easy_example: 'I was reluctant to ask for help.', easy_example_arabic: 'كنت مترددًا في طلب المساعدة.',
  },
  {
    term: 'take something for granted', item_type: 'idiom', part_of_speech: 'verb phrase', level: 'B2', usefulness: 90, topic: 'daily',
    pronunciation: '/teɪk ˈsʌmθɪŋ fər ˈɡrɑːntɪd/', arabic: 'يعتبر الشيء أمرًا مسلّمًا به (ولا يقدّره)',
    simple_english: 'To expect something to always be there and not appreciate it.',
    similar: [
      { word: 'not appreciate', arabic: 'لا يقدّر' },
      { word: 'assume', arabic: 'يفترض', note: 'assume = think something is true; it doesn’t include “not valuing it”.' },
    ],
    example: 'We often take our health for granted until we get sick.',
    example_arabic: 'غالبًا ما نعتبر صحتنا أمرًا مسلّمًا به حتى نمرض.',
    easy_example: 'Don’t take your friends for granted.', easy_example_arabic: 'لا تعتبر وجود أصدقائك أمرًا مضمونًا.',
  },
  {
    term: 'figure something out', item_type: 'phrasal verb', part_of_speech: 'verb', level: 'B1', usefulness: 95, topic: 'daily',
    pronunciation: '/ˈfɪɡər ˈsʌmθɪŋ aʊt/', arabic: 'يكتشف / يجد الحل / يفهم',
    simple_english: 'To understand something or find the answer after thinking.',
    similar: [
      { word: 'understand', arabic: 'يفهم' },
      { word: 'solve', arabic: 'يحل', note: 'solve is for problems; figure out works for problems and for understanding people or situations.' },
      { word: 'find out', arabic: 'يكتشف', note: 'find out = get information; figure out = think until you understand.' },
    ],
    example: 'It took me a week to figure out how the new system works.',
    example_arabic: 'استغرق مني أسبوعًا لأفهم كيف يعمل النظام الجديد.',
    easy_example: 'I can’t figure out this math problem.', easy_example_arabic: 'لا أستطيع حل مسألة الرياضيات هذه.',
  },
  {
    term: 'come across', item_type: 'phrasal verb', part_of_speech: 'verb', level: 'B1', usefulness: 87, topic: 'daily',
    pronunciation: '/kʌm əˈkrɒs/', arabic: 'يصادف / يعثر على (بالصدفة)',
    simple_english: 'To find or meet something by chance.',
    similar: [
      { word: 'find', arabic: 'يجد', note: 'come across adds “by chance”.' },
      { word: 'meet by chance', arabic: 'يقابل صدفة' },
    ],
    example: 'I came across an interesting article about sleep yesterday.',
    example_arabic: 'صادفت مقالًا مثيرًا للاهتمام عن النوم أمس.',
    easy_example: 'I came across my old photos.', easy_example_arabic: 'عثرت على صوري القديمة.',
  },
  {
    term: 'overwhelmed', item_type: 'word', part_of_speech: 'adjective', level: 'B2', usefulness: 89, topic: 'emotions',
    pronunciation: '/ˌəʊvəˈwelmd/', arabic: 'مُثقَل / مغمور بالضغط',
    simple_english: 'Feeling that there is too much to deal with.',
    similar: [
      { word: 'stressed', arabic: 'متوتر', note: 'overwhelmed is stronger: too much, can’t cope.' },
      { word: 'too busy', arabic: 'مشغول جدًا' },
    ],
    example: 'When I started the job, I felt completely overwhelmed by emails.',
    example_arabic: 'عندما بدأت العمل، شعرت أنني غارق تمامًا في الرسائل.',
    easy_example: 'She felt overwhelmed with homework.', easy_example_arabic: 'شعرت بأنها مثقلة بالواجبات.',
  },
  {
    term: 'prioritize', item_type: 'word', part_of_speech: 'verb', level: 'B2', usefulness: 90, topic: 'work',
    pronunciation: '/praɪˈɒrətaɪz/', arabic: 'يرتّب حسب الأولوية',
    simple_english: 'To decide which things are most important and do them first.',
    similar: [
      { word: 'focus on', arabic: 'يركّز على' },
      { word: 'put first', arabic: 'يضع في المقدمة' },
    ],
    example: 'You need to prioritize the tasks that have a deadline this week.',
    example_arabic: 'عليك أن تعطي الأولوية للمهام التي موعدها النهائي هذا الأسبوع.',
    easy_example: 'Prioritize your sleep.', easy_example_arabic: 'اجعل نومك أولوية.',
  },
  {
    term: 'procrastinate', item_type: 'word', part_of_speech: 'verb', level: 'C1', usefulness: 82, topic: 'work',
    pronunciation: '/prəˈkræstɪneɪt/', arabic: 'يماطل / يؤجّل عمل اليوم إلى الغد',
    simple_english: 'To delay doing something you should do, usually because it is boring or hard.',
    similar: [
      { word: 'put off', arabic: 'يؤجّل' },
      { word: 'delay', arabic: 'يؤخّر', note: 'delay can be for a good reason; procrastinate suggests a bad habit.' },
    ],
    example: 'I tend to procrastinate when a task feels too big.',
    example_arabic: 'أميل إلى المماطلة عندما تبدو المهمة كبيرة جدًا.',
    easy_example: 'Stop procrastinating and start now.', easy_example_arabic: 'توقّف عن التأجيل وابدأ الآن.',
  },
  {
    term: 'get the hang of something', item_type: 'idiom', part_of_speech: 'verb phrase', level: 'B2', usefulness: 84, topic: 'daily',
    pronunciation: '/ɡet ðə hæŋ əv ˈsʌmθɪŋ/', arabic: 'يتقن الشيء / يعتاد عليه بعد تجربة',
    simple_english: 'To learn how to do something after some practice.',
    similar: [
      { word: 'learn', arabic: 'يتعلّم' },
      { word: 'get used to', arabic: 'يعتاد على', note: 'get used to = it stops feeling strange; get the hang of = you can do it well.' },
    ],
    example: 'Once you get the hang of it, the software is easy to use.',
    example_arabic: 'بمجرد أن تعتاد عليه، يصبح البرنامج سهل الاستخدام.',
    easy_example: 'I’m getting the hang of driving.', easy_example_arabic: 'بدأت أتقن القيادة.',
  },
  {
    term: 'feasible', item_type: 'word', part_of_speech: 'adjective', level: 'C1', usefulness: 78, topic: 'business',
    pronunciation: '/ˈfiːzəbl/', arabic: 'ممكن التنفيذ / قابل للتطبيق',
    simple_english: 'Possible and practical to do.',
    similar: [
      { word: 'possible', arabic: 'ممكن' },
      { word: 'realistic', arabic: 'واقعي' },
    ],
    example: 'Is it feasible to finish the project before March?',
    example_arabic: 'هل من الممكن إنهاء المشروع قبل مارس؟',
    easy_example: 'The plan is not feasible.', easy_example_arabic: 'الخطة غير قابلة للتنفيذ.',
  },
  {
    term: 'deadline', item_type: 'word', part_of_speech: 'noun', level: 'B1', usefulness: 92, topic: 'work',
    pronunciation: '/ˈdedlaɪn/', arabic: 'الموعد النهائي',
    simple_english: 'The time or date by which something must be finished.',
    similar: [{ word: 'due date', arabic: 'تاريخ التسليم' }],
    example: 'The deadline for the report is Friday at noon.',
    example_arabic: 'الموعد النهائي للتقرير هو الجمعة ظهرًا.',
    easy_example: 'I missed the deadline.', easy_example_arabic: 'فاتني الموعد النهائي.',
  },
  {
    term: 'keep up with', item_type: 'phrasal verb', part_of_speech: 'verb', level: 'B1', usefulness: 86, topic: 'daily',
    pronunciation: '/kiːp ʌp wɪð/', arabic: 'يواكب / يلحق بـ',
    simple_english: 'To move or progress at the same speed as someone or something.',
    similar: [
      { word: 'follow', arabic: 'يتابع' },
      { word: 'stay up to date', arabic: 'يبقى على اطلاع', note: 'used for news and information.' },
    ],
    example: 'It’s hard to keep up with all the changes in technology.',
    example_arabic: 'من الصعب مواكبة كل التغييرات في التكنولوجيا.',
    easy_example: 'Walk slower, I can’t keep up with you!', easy_example_arabic: 'امشِ أبطأ، لا أستطيع اللحاق بك!',
  },
  {
    term: 'burnout', item_type: 'word', part_of_speech: 'noun', level: 'B2', usefulness: 83, topic: 'work',
    pronunciation: '/ˈbɜːnaʊt/', arabic: 'الإرهاق والاحتراق النفسي (من العمل)',
    simple_english: 'Extreme tiredness caused by working too hard for too long.',
    similar: [
      { word: 'exhaustion', arabic: 'إنهاك' },
      { word: 'very tired', arabic: 'متعب جدًا', note: 'burnout is long-term and also emotional.' },
    ],
    example: 'Working twelve hours a day will lead to burnout.',
    example_arabic: 'العمل اثنتي عشرة ساعة يوميًا سيؤدي إلى الاحتراق النفسي.',
    easy_example: 'Take breaks to avoid burnout.', easy_example_arabic: 'خذ فترات راحة لتجنّب الإرهاق.',
  },
  {
    term: 'set aside', item_type: 'phrasal verb', part_of_speech: 'verb', level: 'B2', usefulness: 80, topic: 'daily',
    pronunciation: '/set əˈsaɪd/', arabic: 'يخصّص (وقتًا أو مالًا)',
    simple_english: 'To keep time or money for a special purpose.',
    similar: [
      { word: 'save', arabic: 'يدّخر', note: 'save is mostly for money.' },
      { word: 'keep for', arabic: 'يحتفظ لـ' },
    ],
    example: 'Try to set aside thirty minutes every morning for deep work.',
    example_arabic: 'حاول أن تخصّص ثلاثين دقيقة كل صباح للعمل المركّز.',
    easy_example: 'I set aside some money every month.', easy_example_arabic: 'أخصّص بعض المال كل شهر.',
  },
  {
    term: 'distraction', item_type: 'word', part_of_speech: 'noun', level: 'B2', usefulness: 85, topic: 'daily',
    pronunciation: '/dɪˈstrækʃn/', arabic: 'مصدر تشتيت / إلهاء',
    simple_english: 'Something that takes your attention away from what you are doing.',
    similar: [{ word: 'interruption', arabic: 'مقاطعة', note: 'interruption stops you; distraction pulls your attention.' }],
    example: 'My phone is the biggest distraction when I study.',
    example_arabic: 'هاتفي هو أكبر مصدر للتشتيت عندما أذاكر.',
    easy_example: 'Music can be a distraction.', easy_example_arabic: 'قد تكون الموسيقى مصدر إلهاء.',
  },
  {
    term: 'consistent', item_type: 'word', part_of_speech: 'adjective', level: 'B2', usefulness: 88, topic: 'daily',
    pronunciation: '/kənˈsɪstənt/', arabic: 'منتظم / ثابت',
    simple_english: 'Always behaving or happening in the same way.',
    similar: [
      { word: 'regular', arabic: 'منتظم' },
      { word: 'steady', arabic: 'ثابت' },
    ],
    example: 'Being consistent matters more than being perfect.',
    example_arabic: 'الاستمرارية أهم من الكمال.',
    easy_example: 'Be consistent with your practice.', easy_example_arabic: 'كن منتظمًا في تدريبك.',
  },
  {
    term: 'in the long run', item_type: 'expression', part_of_speech: 'adverb phrase', level: 'B2', usefulness: 86, topic: 'daily',
    pronunciation: '/ɪn ðə lɒŋ rʌn/', arabic: 'على المدى البعيد',
    simple_english: 'After a long period of time; in the future.',
    similar: [{ word: 'eventually', arabic: 'في النهاية' }, { word: 'in the future', arabic: 'في المستقبل' }],
    example: 'Small habits save you a lot of time in the long run.',
    example_arabic: 'العادات الصغيرة توفر عليك الكثير من الوقت على المدى البعيد.',
    easy_example: 'It will help you in the long run.', easy_example_arabic: 'سيفيدك على المدى البعيد.',
  },
  {
    term: 'cope with', item_type: 'phrasal verb', part_of_speech: 'verb', level: 'B2', usefulness: 87, topic: 'emotions',
    pronunciation: '/kəʊp wɪð/', arabic: 'يتعامل مع (صعوبة) / يتحمّل',
    simple_english: 'To deal successfully with a difficult situation.',
    similar: [{ word: 'deal with', arabic: 'يتعامل مع' }, { word: 'handle', arabic: 'يتحكّم في / يدير' }],
    example: 'Everyone has their own way to cope with stress.',
    example_arabic: 'لكل شخص طريقته الخاصة للتعامل مع التوتر.',
    easy_example: 'How do you cope with pressure?', easy_example_arabic: 'كيف تتعامل مع الضغط؟',
  },
  {
    term: 'efficient', item_type: 'word', part_of_speech: 'adjective', level: 'B2', usefulness: 86, topic: 'work',
    pronunciation: '/ɪˈfɪʃnt/', arabic: 'فعّال / كفء (بدون إهدار)',
    simple_english: 'Working well without wasting time, money or energy.',
    similar: [
      { word: 'productive', arabic: 'منتج' },
      { word: 'effective', arabic: 'فعّال', note: 'effective = gets the result; efficient = gets it without waste.' },
    ],
    example: 'We need a more efficient way to handle customer requests.',
    example_arabic: 'نحتاج طريقة أكثر كفاءة للتعامل مع طلبات العملاء.',
    easy_example: 'This car is very efficient.', easy_example_arabic: 'هذه السيارة اقتصادية جدًا.',
  },

  // ---------- Video 2: university / learning / science ----------
  {
    term: 'acquire', item_type: 'word', part_of_speech: 'verb', level: 'B2', usefulness: 82, topic: 'academic',
    pronunciation: '/əˈkwaɪər/', arabic: 'يكتسب',
    simple_english: 'To get or gain something, such as a skill or knowledge.',
    similar: [{ word: 'get', arabic: 'يحصل على' }, { word: 'learn', arabic: 'يتعلّم', note: 'acquire is more formal.' }],
    example: 'Children acquire language naturally by listening.',
    example_arabic: 'يكتسب الأطفال اللغة بشكل طبيعي عن طريق الاستماع.',
    easy_example: 'She acquired new skills at work.', easy_example_arabic: 'اكتسبت مهارات جديدة في العمل.',
  },
  {
    term: 'retain', item_type: 'word', part_of_speech: 'verb', level: 'C1', usefulness: 80, topic: 'academic',
    pronunciation: '/rɪˈteɪn/', arabic: 'يحتفظ بـ / يتذكّر (المعلومة)',
    simple_english: 'To keep or continue to have something, especially information.',
    similar: [{ word: 'keep', arabic: 'يحتفظ' }, { word: 'remember', arabic: 'يتذكّر' }],
    example: 'Testing yourself helps you retain information for longer.',
    example_arabic: 'اختبار نفسك يساعدك على الاحتفاظ بالمعلومات لمدة أطول.',
    easy_example: 'I can’t retain new words easily.', easy_example_arabic: 'لا أستطيع تذكّر الكلمات الجديدة بسهولة.',
  },
  {
    term: 'evidence', item_type: 'word', part_of_speech: 'noun', level: 'B1', usefulness: 88, topic: 'academic',
    pronunciation: '/ˈevɪdəns/', arabic: 'دليل / أدلة',
    simple_english: 'Facts or information that show something is true.',
    similar: [{ word: 'proof', arabic: 'إثبات', note: 'proof shows something is 100% true; evidence supports it.' }],
    example: 'There is strong evidence that sleep improves memory.',
    example_arabic: 'هناك أدلة قوية على أن النوم يحسّن الذاكرة.',
    easy_example: 'Do you have any evidence?', easy_example_arabic: 'هل لديك أي دليل؟',
  },
  {
    term: 'counterintuitive', item_type: 'word', part_of_speech: 'adjective', level: 'C1', usefulness: 72, topic: 'academic',
    pronunciation: '/ˌkaʊntərɪnˈtjuːɪtɪv/', arabic: 'مخالف للبديهة / عكس المتوقّع',
    simple_english: 'Different from what you would naturally expect.',
    similar: [{ word: 'surprising', arabic: 'مفاجئ' }, { word: 'unexpected', arabic: 'غير متوقّع' }],
    example: 'It sounds counterintuitive, but taking breaks makes you work faster.',
    example_arabic: 'يبدو الأمر عكس المتوقّع، لكن أخذ فترات راحة يجعلك تعمل أسرع.',
    easy_example: 'The answer was counterintuitive.', easy_example_arabic: 'كانت الإجابة عكس المتوقع.',
  },
  {
    term: 'point out', item_type: 'phrasal verb', part_of_speech: 'verb', level: 'B1', usefulness: 87, topic: 'academic',
    pronunciation: '/pɔɪnt aʊt/', arabic: 'يشير إلى / يلفت الانتباه إلى',
    simple_english: 'To tell someone about a fact or mistake they had not noticed.',
    similar: [{ word: 'mention', arabic: 'يذكر' }, { word: 'show', arabic: 'يُظهر' }],
    example: 'The researcher pointed out that most students study the wrong way.',
    example_arabic: 'أشار الباحث إلى أن معظم الطلاب يذاكرون بطريقة خاطئة.',
    easy_example: 'He pointed out my mistake.', easy_example_arabic: 'نبّهني إلى خطئي.',
  },
  {
    term: 'struggle', item_type: 'word', part_of_speech: 'verb', level: 'B1', usefulness: 91, topic: 'daily',
    pronunciation: '/ˈstrʌɡl/', arabic: 'يعاني / يجد صعوبة في',
    simple_english: 'To try very hard to do something that is difficult.',
    similar: [{ word: 'have difficulty', arabic: 'يواجه صعوبة' }, { word: 'find it hard', arabic: 'يجده صعبًا' }],
    example: 'Many students struggle to concentrate for more than twenty minutes.',
    example_arabic: 'يجد كثير من الطلاب صعوبة في التركيز لأكثر من عشرين دقيقة.',
    easy_example: 'I struggle with grammar.', easy_example_arabic: 'أعاني مع القواعد.',
  },
  {
    term: 'misconception', item_type: 'word', part_of_speech: 'noun', level: 'C1', usefulness: 78, topic: 'academic',
    pronunciation: '/ˌmɪskənˈsepʃn/', arabic: 'مفهوم خاطئ / اعتقاد خاطئ',
    simple_english: 'An idea that is wrong because it is based on a misunderstanding.',
    similar: [{ word: 'wrong idea', arabic: 'فكرة خاطئة' }, { word: 'myth', arabic: 'خرافة', note: 'myth = a common false belief, often old.' }],
    example: 'A common misconception is that rereading notes is the best way to learn.',
    example_arabic: 'من المفاهيم الخاطئة الشائعة أن إعادة قراءة الملاحظات هي أفضل طريقة للتعلّم.',
    easy_example: 'That is a misconception.', easy_example_arabic: 'هذا اعتقاد خاطئ.',
  },
  {
    term: 'break down', item_type: 'phrasal verb', part_of_speech: 'verb', level: 'B2', usefulness: 84, topic: 'academic',
    pronunciation: '/breɪk daʊn/', arabic: 'يقسّم (إلى أجزاء أصغر) / يحلّل',
    simple_english: 'To divide something into smaller parts so it is easier to understand.',
    similar: [{ word: 'divide', arabic: 'يقسّم' }, { word: 'split', arabic: 'يجزّئ' }],
    example: 'Break down big topics into small questions you can answer.',
    example_arabic: 'قسّم المواضيع الكبيرة إلى أسئلة صغيرة يمكنك الإجابة عنها.',
    easy_example: 'Let’s break the problem down.', easy_example_arabic: 'لنقسّم المشكلة إلى أجزاء.',
  },
  {
    term: 'crucial', item_type: 'word', part_of_speech: 'adjective', level: 'B2', usefulness: 87, topic: 'academic',
    pronunciation: '/ˈkruːʃl/', arabic: 'حاسم / بالغ الأهمية',
    simple_english: 'Extremely important.',
    similar: [{ word: 'very important', arabic: 'مهم جدًا' }, { word: 'essential', arabic: 'أساسي' }],
    example: 'Sleep is crucial for turning short-term memories into long-term ones.',
    example_arabic: 'النوم بالغ الأهمية لتحويل الذكريات قصيرة المدى إلى طويلة المدى.',
    easy_example: 'This step is crucial.', easy_example_arabic: 'هذه الخطوة حاسمة.',
  },
  {
    term: 'approach', item_type: 'word', part_of_speech: 'noun', level: 'B2', usefulness: 89, topic: 'academic',
    pronunciation: '/əˈprəʊtʃ/', arabic: 'أسلوب / طريقة للتعامل',
    simple_english: 'A way of dealing with something.',
    similar: [{ word: 'way', arabic: 'طريقة' }, { word: 'method', arabic: 'منهج', note: 'method is more step-by-step.' }],
    example: 'This approach to studying is based on research.',
    example_arabic: 'هذا الأسلوب في المذاكرة مبني على الأبحاث.',
    easy_example: 'Let’s try a different approach.', easy_example_arabic: 'لنجرّب طريقة مختلفة.',
  },
  {
    term: 'come up with', item_type: 'phrasal verb', part_of_speech: 'verb', level: 'B1', usefulness: 92, topic: 'daily',
    pronunciation: '/kʌm ʌp wɪð/', arabic: 'يبتكر / يخطر له (فكرة أو حل)',
    simple_english: 'To think of an idea, plan or answer.',
    similar: [{ word: 'think of', arabic: 'يفكّر في' }, { word: 'create', arabic: 'يبتكر' }],
    example: 'Try to come up with your own examples for each new word.',
    example_arabic: 'حاول أن تبتكر أمثلتك الخاصة لكل كلمة جديدة.',
    easy_example: 'She came up with a great idea.', easy_example_arabic: 'خطرت لها فكرة رائعة.',
  },
  {
    term: 'outcome', item_type: 'word', part_of_speech: 'noun', level: 'B2', usefulness: 83, topic: 'academic',
    pronunciation: '/ˈaʊtkʌm/', arabic: 'نتيجة / محصّلة',
    simple_english: 'The result of an action or process.',
    similar: [{ word: 'result', arabic: 'نتيجة' }],
    example: 'Students who tested themselves had much better outcomes.',
    example_arabic: 'الطلاب الذين اختبروا أنفسهم حصلوا على نتائج أفضل بكثير.',
    easy_example: 'We are happy with the outcome.', easy_example_arabic: 'نحن راضون عن النتيجة.',
  },
  {
    term: 'rely on', item_type: 'phrasal verb', part_of_speech: 'verb', level: 'B1', usefulness: 88, topic: 'daily',
    pronunciation: '/rɪˈlaɪ ɒn/', arabic: 'يعتمد على',
    simple_english: 'To need or trust someone or something.',
    similar: [{ word: 'depend on', arabic: 'يعتمد على' }, { word: 'trust', arabic: 'يثق بـ' }],
    example: 'Don’t rely on your memory alone — write things down.',
    example_arabic: 'لا تعتمد على ذاكرتك وحدها — دوّن الأشياء.',
    easy_example: 'You can rely on me.', easy_example_arabic: 'يمكنك الاعتماد عليّ.',
  },
  {
    term: 'significant', item_type: 'word', part_of_speech: 'adjective', level: 'B2', usefulness: 86, topic: 'academic',
    pronunciation: '/sɪɡˈnɪfɪkənt/', arabic: 'كبير / ملحوظ / مهم',
    simple_english: 'Large or important enough to have an effect.',
    similar: [{ word: 'important', arabic: 'مهم' }, { word: 'big', arabic: 'كبير' }],
    example: 'The study found a significant improvement in test scores.',
    example_arabic: 'وجدت الدراسة تحسنًا ملحوظًا في نتائج الاختبارات.',
    easy_example: 'It made a significant difference.', easy_example_arabic: 'أحدث فرقًا كبيرًا.',
  },
  {
    term: 'hinder', item_type: 'word', part_of_speech: 'verb', level: 'C1', usefulness: 72, topic: 'academic',
    pronunciation: '/ˈhɪndər/', arabic: 'يعيق / يعرقل',
    simple_english: 'To make it difficult for something to happen or develop.',
    similar: [{ word: 'slow down', arabic: 'يبطئ' }, { word: 'block', arabic: 'يمنع', note: 'block stops it completely; hinder only makes it harder.' }],
    example: 'Multitasking can hinder your ability to learn.',
    example_arabic: 'تعدد المهام قد يعيق قدرتك على التعلّم.',
    easy_example: 'Noise hinders my focus.', easy_example_arabic: 'الضوضاء تعيق تركيزي.',
  },
  {
    term: 'make sense of', item_type: 'expression', part_of_speech: 'verb phrase', level: 'B2', usefulness: 85, topic: 'daily',
    pronunciation: '/meɪk sens əv/', arabic: 'يفهم / يستوعب (شيئًا معقّدًا)',
    simple_english: 'To understand something that is difficult or confusing.',
    similar: [{ word: 'understand', arabic: 'يفهم' }],
    example: 'Drawing a diagram helps me make sense of complex ideas.',
    example_arabic: 'رسم مخطط يساعدني على استيعاب الأفكار المعقدة.',
    easy_example: 'I can’t make sense of this letter.', easy_example_arabic: 'لا أستطيع فهم هذه الرسالة.',
  },
  {
    term: 'rule of thumb', item_type: 'idiom', part_of_speech: 'noun phrase', level: 'C1', usefulness: 76, topic: 'daily',
    pronunciation: '/ruːl əv θʌm/', arabic: 'قاعدة عامة (مبنية على الخبرة)',
    simple_english: 'A practical rule based on experience, not exact science.',
    similar: [{ word: 'general rule', arabic: 'قاعدة عامة' }, { word: 'guideline', arabic: 'إرشاد' }],
    example: 'A good rule of thumb is to review new words after one day.',
    example_arabic: 'من القواعد العامة الجيدة أن تراجع الكلمات الجديدة بعد يوم واحد.',
    easy_example: 'As a rule of thumb, drink more water.', easy_example_arabic: 'كقاعدة عامة، اشرب ماءً أكثر.',
  },

  // ---------- Video 3: business / media / communication ----------
  {
    term: 'negotiate', item_type: 'word', part_of_speech: 'verb', level: 'B2', usefulness: 85, topic: 'business',
    pronunciation: '/nɪˈɡəʊʃieɪt/', arabic: 'يتفاوض',
    simple_english: 'To discuss something to reach an agreement.',
    similar: [{ word: 'discuss', arabic: 'يناقش' }, { word: 'bargain', arabic: 'يساوم', note: 'bargain is usually about price.' }],
    example: 'Always negotiate your salary before accepting a job offer.',
    example_arabic: 'تفاوض دائمًا على راتبك قبل قبول عرض العمل.',
    easy_example: 'We negotiated a better price.', easy_example_arabic: 'تفاوضنا على سعر أفضل.',
  },
  {
    term: 'leverage', item_type: 'word', part_of_speech: 'verb', level: 'C1', usefulness: 74, topic: 'business',
    pronunciation: '/ˈliːvərɪdʒ/', arabic: 'يستغلّ / يستفيد من (بذكاء)',
    simple_english: 'To use something you have to get the best result.',
    similar: [{ word: 'use', arabic: 'يستخدم' }, { word: 'make the most of', arabic: 'يستفيد أقصى استفادة' }],
    example: 'Small companies can leverage social media to reach new customers.',
    example_arabic: 'يمكن للشركات الصغيرة الاستفادة من وسائل التواصل للوصول إلى عملاء جدد.',
    easy_example: 'Leverage your experience.', easy_example_arabic: 'استفد من خبرتك.',
  },
  {
    term: 'stand out', item_type: 'phrasal verb', part_of_speech: 'verb', level: 'B1', usefulness: 88, topic: 'business',
    pronunciation: '/stænd aʊt/', arabic: 'يتميّز / يبرز',
    simple_english: 'To be easy to notice because you are different or better.',
    similar: [{ word: 'be noticed', arabic: 'يُلاحَظ' }, { word: 'be different', arabic: 'يكون مختلفًا' }],
    example: 'Your CV needs to stand out from hundreds of others.',
    example_arabic: 'يجب أن تتميّز سيرتك الذاتية بين مئات السير الأخرى.',
    easy_example: 'Her red dress stood out.', easy_example_arabic: 'برز فستانها الأحمر.',
  },
  {
    term: 'pitch', item_type: 'word', part_of_speech: 'noun', level: 'B2', usefulness: 76, topic: 'business',
    pronunciation: '/pɪtʃ/', arabic: 'عرض تقديمي مقنع (لفكرة أو منتج)',
    simple_english: 'A short talk to persuade people to buy or support something.',
    similar: [{ word: 'presentation', arabic: 'عرض تقديمي', note: 'a pitch is shorter and tries to sell.' }],
    example: 'She gave a two-minute pitch to the investors.',
    example_arabic: 'قدّمت عرضًا مقنعًا لمدة دقيقتين أمام المستثمرين.',
    easy_example: 'His pitch was very clear.', easy_example_arabic: 'كان عرضه واضحًا جدًا.',
  },
  {
    term: 'persuasive', item_type: 'word', part_of_speech: 'adjective', level: 'B2', usefulness: 81, topic: 'business',
    pronunciation: '/pəˈsweɪsɪv/', arabic: 'مُقنِع',
    simple_english: 'Able to make people agree or believe something.',
    similar: [{ word: 'convincing', arabic: 'مقنع' }],
    example: 'A persuasive story is more powerful than a list of facts.',
    example_arabic: 'القصة المقنعة أقوى من قائمة حقائق.',
    easy_example: 'She is very persuasive.', easy_example_arabic: 'إنها مقنعة جدًا.',
  },
  {
    term: 'get your point across', item_type: 'idiom', part_of_speech: 'verb phrase', level: 'B2', usefulness: 83, topic: 'business',
    pronunciation: '/ɡet jɔː pɔɪnt əˈkrɒs/', arabic: 'يوصل فكرته بوضوح',
    simple_english: 'To make other people understand your idea.',
    similar: [{ word: 'explain clearly', arabic: 'يشرح بوضوح' }, { word: 'communicate', arabic: 'يتواصل' }],
    example: 'Use simple words to get your point across quickly.',
    example_arabic: 'استخدم كلمات بسيطة لتوصل فكرتك بسرعة.',
    easy_example: 'I couldn’t get my point across.', easy_example_arabic: 'لم أستطع إيصال فكرتي.',
  },
  {
    term: 'stakeholder', item_type: 'word', part_of_speech: 'noun', level: 'C1', usefulness: 73, topic: 'business',
    pronunciation: '/ˈsteɪkhəʊldər/', arabic: 'صاحب مصلحة / طرف معنيّ',
    simple_english: 'A person or group who is affected by or interested in a project or company.',
    similar: [{ word: 'partner', arabic: 'شريك', note: 'partners are only one kind of stakeholder.' }],
    example: 'Keep every stakeholder informed about the timeline.',
    example_arabic: 'أبقِ كل الأطراف المعنية على علم بالجدول الزمني.',
    easy_example: 'Customers are stakeholders too.', easy_example_arabic: 'العملاء أيضًا أصحاب مصلحة.',
  },
  {
    term: 'compelling', item_type: 'word', part_of_speech: 'adjective', level: 'C1', usefulness: 77, topic: 'media',
    pronunciation: '/kəmˈpelɪŋ/', arabic: 'مُقنع جدًا / آسر للانتباه',
    simple_english: 'So interesting or convincing that you have to pay attention.',
    similar: [{ word: 'convincing', arabic: 'مقنع' }, { word: 'very interesting', arabic: 'مثير جدًا للاهتمام' }],
    example: 'You need a compelling reason for people to watch your video.',
    example_arabic: 'تحتاج سببًا مقنعًا يجعل الناس يشاهدون الفيديو الخاص بك.',
    easy_example: 'It was a compelling story.', easy_example_arabic: 'كانت قصة آسرة.',
  },
  {
    term: 'engagement', item_type: 'word', part_of_speech: 'noun', level: 'B2', usefulness: 78, topic: 'media',
    pronunciation: '/ɪnˈɡeɪdʒmənt/', arabic: 'التفاعل (مع المحتوى)',
    simple_english: 'How much people interact with something, like likes and comments.',
    similar: [{ word: 'interaction', arabic: 'تفاعل' }, { word: 'interest', arabic: 'اهتمام' }],
    example: 'Short videos usually get more engagement on social media.',
    example_arabic: 'عادةً تحصل الفيديوهات القصيرة على تفاعل أكبر في وسائل التواصل.',
    easy_example: 'Engagement went up this week.', easy_example_arabic: 'ارتفع التفاعل هذا الأسبوع.',
  },
  {
    term: 'follow up', item_type: 'phrasal verb', part_of_speech: 'verb', level: 'B2', usefulness: 86, topic: 'business',
    pronunciation: '/ˈfɒləʊ ʌp/', arabic: 'يتابع (بعد اجتماع أو رسالة)',
    simple_english: 'To contact someone again to continue something you started.',
    similar: [{ word: 'check back', arabic: 'يعاود التواصل' }, { word: 'contact again', arabic: 'يتواصل مرة أخرى' }],
    example: 'Always follow up with an email after an interview.',
    example_arabic: 'تابع دائمًا برسالة بريد إلكتروني بعد المقابلة.',
    easy_example: 'I’ll follow up tomorrow.', easy_example_arabic: 'سأتابع غدًا.',
  },
  {
    term: 'on the same page', item_type: 'idiom', part_of_speech: 'adjective phrase', level: 'B2', usefulness: 88, topic: 'business',
    pronunciation: '/ɒn ðə seɪm peɪdʒ/', arabic: 'متّفقون / على نفس الفهم',
    simple_english: 'Agreeing and understanding the situation in the same way.',
    similar: [{ word: 'in agreement', arabic: 'متفقون' }, { word: 'agree', arabic: 'يتفق' }],
    example: 'Let’s have a quick call to make sure we’re on the same page.',
    example_arabic: 'لنُجرِ مكالمة سريعة لنتأكد أننا متفقون.',
    easy_example: 'Are we on the same page?', easy_example_arabic: 'هل نحن متفقون؟',
  },
  {
    term: 'tough call', item_type: 'idiom', part_of_speech: 'noun phrase', level: 'B2', usefulness: 79, topic: 'business',
    pronunciation: '/tʌf kɔːl/', arabic: 'قرار صعب',
    simple_english: 'A difficult decision.',
    similar: [{ word: 'hard decision', arabic: 'قرار صعب' }],
    example: 'Choosing between the two candidates was a tough call.',
    example_arabic: 'كان الاختيار بين المرشحَين قرارًا صعبًا.',
    easy_example: 'It’s a tough call.', easy_example_arabic: 'إنه قرار صعب.',
  },
  {
    term: 'genuine', item_type: 'word', part_of_speech: 'adjective', level: 'B2', usefulness: 84, topic: 'emotions',
    pronunciation: '/ˈdʒenjuɪn/', arabic: 'صادق / حقيقي',
    simple_english: 'Real and sincere, not fake.',
    similar: [{ word: 'real', arabic: 'حقيقي' }, { word: 'honest', arabic: 'صادق' }],
    example: 'People can tell when your interest is genuine.',
    example_arabic: 'يستطيع الناس معرفة متى يكون اهتمامك صادقًا.',
    easy_example: 'He gave me a genuine smile.', easy_example_arabic: 'ابتسم لي ابتسامة صادقة.',
  },
  {
    term: 'trade-off', item_type: 'word', part_of_speech: 'noun', level: 'C1', usefulness: 78, topic: 'business',
    pronunciation: '/ˈtreɪd ɒf/', arabic: 'مقايضة / التضحية بشيء مقابل آخر',
    simple_english: 'A balance between two things you can’t have at the same time.',
    similar: [{ word: 'compromise', arabic: 'حل وسط', note: 'compromise is between people; trade-off is between options.' }],
    example: 'There is always a trade-off between speed and quality.',
    example_arabic: 'هناك دائمًا مقايضة بين السرعة والجودة.',
    easy_example: 'It’s a trade-off.', easy_example_arabic: 'إنها مسألة موازنة.',
  },
  {
    term: 'turn down', item_type: 'phrasal verb', part_of_speech: 'verb', level: 'B1', usefulness: 87, topic: 'daily',
    pronunciation: '/tɜːn daʊn/', arabic: 'يرفض (عرضًا أو طلبًا)',
    simple_english: 'To refuse an offer or request.',
    similar: [{ word: 'refuse', arabic: 'يرفض' }, { word: 'say no to', arabic: 'يقول لا لـ' }],
    example: 'She turned down the offer because the salary was too low.',
    example_arabic: 'رفضت العرض لأن الراتب كان منخفضًا جدًا.',
    easy_example: 'He turned down my invitation.', easy_example_arabic: 'رفض دعوتي.',
  },
  {
    term: 'reach out', item_type: 'phrasal verb', part_of_speech: 'verb', level: 'B2', usefulness: 85, topic: 'business',
    pronunciation: '/riːtʃ aʊt/', arabic: 'يتواصل مع (للمساعدة أو التعارف)',
    simple_english: 'To contact someone, often to offer or ask for help.',
    similar: [{ word: 'contact', arabic: 'يتواصل' }, { word: 'get in touch', arabic: 'يتصل بـ' }],
    example: 'Feel free to reach out if you have any questions.',
    example_arabic: 'لا تتردد في التواصل إذا كان لديك أي أسئلة.',
    easy_example: 'I reached out to my old teacher.', easy_example_arabic: 'تواصلت مع معلمي القديم.',
  },
  {
    term: 'straightforward', item_type: 'word', part_of_speech: 'adjective', level: 'B2', usefulness: 86, topic: 'daily',
    pronunciation: '/ˌstreɪtˈfɔːwəd/', arabic: 'واضح وبسيط / سهل',
    simple_english: 'Easy to understand or do; not complicated.',
    similar: [{ word: 'simple', arabic: 'بسيط' }, { word: 'clear', arabic: 'واضح' }],
    example: 'The process is straightforward once you know the steps.',
    example_arabic: 'العملية بسيطة بمجرد أن تعرف الخطوات.',
    easy_example: 'The instructions are straightforward.', easy_example_arabic: 'التعليمات واضحة وبسيطة.',
  },
  {
    term: 'thrive', item_type: 'word', part_of_speech: 'verb', level: 'C1', usefulness: 76, topic: 'business',
    pronunciation: '/θraɪv/', arabic: 'يزدهر / ينجح بقوة',
    simple_english: 'To grow, develop or be successful.',
    similar: [{ word: 'succeed', arabic: 'ينجح' }, { word: 'grow', arabic: 'ينمو' }],
    example: 'Some people thrive under pressure.',
    example_arabic: 'بعض الناس يزدهرون تحت الضغط.',
    easy_example: 'The business is thriving.', easy_example_arabic: 'العمل مزدهر.',
  },
  {
    term: 'ambiguous', item_type: 'word', part_of_speech: 'adjective', level: 'C1', usefulness: 75, topic: 'academic',
    pronunciation: '/æmˈbɪɡjuəs/', arabic: 'غامض / يحتمل أكثر من معنى',
    simple_english: 'Having more than one possible meaning; not clear.',
    similar: [{ word: 'unclear', arabic: 'غير واضح' }, { word: 'confusing', arabic: 'مربك' }],
    example: 'Avoid ambiguous instructions in your emails.',
    example_arabic: 'تجنّب التعليمات الغامضة في رسائلك.',
    easy_example: 'His answer was ambiguous.', easy_example_arabic: 'كانت إجابته غامضة.',
  },
  {
    term: 'feedback', item_type: 'word', part_of_speech: 'noun', level: 'B1', usefulness: 90, topic: 'work',
    pronunciation: '/ˈfiːdbæk/', arabic: 'ملاحظات / تقييم (لتحسين الأداء)',
    simple_english: 'Comments about how well someone is doing, so they can improve.',
    similar: [{ word: 'comments', arabic: 'تعليقات' }, { word: 'opinion', arabic: 'رأي' }],
    example: 'Ask your manager for honest feedback every month.',
    example_arabic: 'اطلب من مديرك ملاحظات صادقة كل شهر.',
    easy_example: 'Thanks for the feedback.', easy_example_arabic: 'شكرًا على الملاحظات.',
  },
  {
    term: 'bring up', item_type: 'phrasal verb', part_of_speech: 'verb', level: 'B1', usefulness: 85, topic: 'daily',
    pronunciation: '/brɪŋ ʌp/', arabic: 'يطرح (موضوعًا للنقاش)',
    simple_english: 'To start talking about a subject.',
    similar: [{ word: 'mention', arabic: 'يذكر' }, { word: 'raise', arabic: 'يطرح', note: 'raise is more formal.' }],
    example: 'Don’t bring up money in the first meeting.',
    example_arabic: 'لا تطرح موضوع المال في الاجتماع الأول.',
    easy_example: 'She brought up a good point.', easy_example_arabic: 'طرحت نقطة جيدة.',
  },
  {
    term: 'assumption', item_type: 'word', part_of_speech: 'noun', level: 'B2', usefulness: 82, topic: 'academic',
    pronunciation: '/əˈsʌmpʃn/', arabic: 'افتراض',
    simple_english: 'Something you think is true without having proof.',
    similar: [{ word: 'guess', arabic: 'تخمين', note: 'a guess is less certain.' }, { word: 'belief', arabic: 'اعتقاد' }],
    example: 'Don’t make assumptions about what the customer wants.',
    example_arabic: 'لا تضع افتراضات حول ما يريده العميل.',
    easy_example: 'That’s just an assumption.', easy_example_arabic: 'هذا مجرد افتراض.',
  },
];
